//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG.Servisi.MUPParking {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="MUP.Parking.WebServiceInterface", Namespace="http://MUP.Parking.WebService", ConfigurationName="MUPParking.MUPParkingWebServiceInterface")]
    public interface MUPParkingWebServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MUP.Parking.WebService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PG.Servisi.MUPParking.VoziloResponse Vozilo(PG.Servisi.MUPParking.VoziloRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://MUP.Parking.WebService", ReplyAction="*")]
        System.Threading.Tasks.Task<PG.Servisi.MUPParking.VoziloResponse> VoziloAsync(PG.Servisi.MUPParking.VoziloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MUP.Parking/Upit")]
    public partial class UpitIdentifikacija : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string institucijaOIBField;
        
        private int svrhaPretrageField;
        
        private string lokacijaPrekrsajaField;
        
        private System.DateTime datumPrekrsajaField;
        
        public UpitIdentifikacija() {
            this.svrhaPretrageField = 40;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InstitucijaOIB {
            get {
                return this.institucijaOIBField;
            }
            set {
                this.institucijaOIBField = value;
                this.RaisePropertyChanged("InstitucijaOIB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SvrhaPretrage {
            get {
                return this.svrhaPretrageField;
            }
            set {
                this.svrhaPretrageField = value;
                this.RaisePropertyChanged("SvrhaPretrage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LokacijaPrekrsaja {
            get {
                return this.lokacijaPrekrsajaField;
            }
            set {
                this.lokacijaPrekrsajaField = value;
                this.RaisePropertyChanged("LokacijaPrekrsaja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime DatumPrekrsaja {
            get {
                return this.datumPrekrsajaField;
            }
            set {
                this.datumPrekrsajaField = value;
                this.RaisePropertyChanged("DatumPrekrsaja");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MUP.Parking/Odgovor")]
    public partial class OdgovorVozilo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string registarskaOznakaField;
        
        private string vrstaVozilaField;
        
        private string markaVozilaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RegistarskaOznaka {
            get {
                return this.registarskaOznakaField;
            }
            set {
                this.registarskaOznakaField = value;
                this.RaisePropertyChanged("RegistarskaOznaka");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VrstaVozila {
            get {
                return this.vrstaVozilaField;
            }
            set {
                this.vrstaVozilaField = value;
                this.RaisePropertyChanged("VrstaVozila");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MarkaVozila {
            get {
                return this.markaVozilaField;
            }
            set {
                this.markaVozilaField = value;
                this.RaisePropertyChanged("MarkaVozila");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MUP.Parking/Odgovor")]
    public partial class Adresa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string drzavaField;
        
        private string opcinaField;
        
        private string mjestoField;
        
        private string ulicaBrojField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Drzava {
            get {
                return this.drzavaField;
            }
            set {
                this.drzavaField = value;
                this.RaisePropertyChanged("Drzava");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Opcina {
            get {
                return this.opcinaField;
            }
            set {
                this.opcinaField = value;
                this.RaisePropertyChanged("Opcina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Mjesto {
            get {
                return this.mjestoField;
            }
            set {
                this.mjestoField = value;
                this.RaisePropertyChanged("Mjesto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UlicaBroj {
            get {
                return this.ulicaBrojField;
            }
            set {
                this.ulicaBrojField = value;
                this.RaisePropertyChanged("UlicaBroj");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MUP.Parking/Odgovor")]
    public partial class OdgovorVlasnik : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string imeVlasnikaField;
        
        private string prezimeVlasnikaField;
        
        private string indikatorVKField;
        
        private string nazivVlasnikaField;
        
        private string oIBVlasnikaField;
        
        private Adresa adresaVlasnikaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ImeVlasnika {
            get {
                return this.imeVlasnikaField;
            }
            set {
                this.imeVlasnikaField = value;
                this.RaisePropertyChanged("ImeVlasnika");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PrezimeVlasnika {
            get {
                return this.prezimeVlasnikaField;
            }
            set {
                this.prezimeVlasnikaField = value;
                this.RaisePropertyChanged("PrezimeVlasnika");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IndikatorVK {
            get {
                return this.indikatorVKField;
            }
            set {
                this.indikatorVKField = value;
                this.RaisePropertyChanged("IndikatorVK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NazivVlasnika {
            get {
                return this.nazivVlasnikaField;
            }
            set {
                this.nazivVlasnikaField = value;
                this.RaisePropertyChanged("NazivVlasnika");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OIBVlasnika {
            get {
                return this.oIBVlasnikaField;
            }
            set {
                this.oIBVlasnikaField = value;
                this.RaisePropertyChanged("OIBVlasnika");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Adresa AdresaVlasnika {
            get {
                return this.adresaVlasnikaField;
            }
            set {
                this.adresaVlasnikaField = value;
                this.RaisePropertyChanged("AdresaVlasnika");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MUP.Parking/Odgovor")]
    public partial class Odgovor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OdgovorVlasnik[] vlasnikVoziloField;
        
        private OdgovorVozilo osnovnoVoziloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VlasnikVozilo", Order=0)]
        public OdgovorVlasnik[] VlasnikVozilo {
            get {
                return this.vlasnikVoziloField;
            }
            set {
                this.vlasnikVoziloField = value;
                this.RaisePropertyChanged("VlasnikVozilo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OdgovorVozilo OsnovnoVozilo {
            get {
                return this.osnovnoVoziloField;
            }
            set {
                this.osnovnoVoziloField = value;
                this.RaisePropertyChanged("OsnovnoVozilo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MUP.Parking/Upit")]
    public partial class PretragaParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string registarskaOznakaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RegistarskaOznaka {
            get {
                return this.registarskaOznakaField;
            }
            set {
                this.registarskaOznakaField = value;
                this.RaisePropertyChanged("RegistarskaOznaka");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VoziloRequest", WrapperNamespace="http://MUP.Parking/Service", IsWrapped=true)]
    public partial class VoziloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MUP.Parking/Service", Order=0)]
        public PG.Servisi.MUPParking.UpitIdentifikacija zaglavlje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MUP.Parking/Service", Order=1)]
        public PG.Servisi.MUPParking.PretragaParams Vozilo;
        
        public VoziloRequest() {
        }
        
        public VoziloRequest(PG.Servisi.MUPParking.UpitIdentifikacija zaglavlje, PG.Servisi.MUPParking.PretragaParams Vozilo) {
            this.zaglavlje = zaglavlje;
            this.Vozilo = Vozilo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VoziloResponse", WrapperNamespace="http://MUP.Parking/Service", IsWrapped=true)]
    public partial class VoziloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MUP.Parking/Service", Order=0)]
        public PG.Servisi.MUPParking.Odgovor OdgovorVozilo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MUP.Parking/Service", Order=1)]
        public int Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MUP.Parking/Service", Order=2)]
        public string StatusMessage;
        
        public VoziloResponse() {
        }
        
        public VoziloResponse(PG.Servisi.MUPParking.Odgovor OdgovorVozilo, int Status, string StatusMessage) {
            this.OdgovorVozilo = OdgovorVozilo;
            this.Status = Status;
            this.StatusMessage = StatusMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MUPParkingWebServiceInterfaceChannel : PG.Servisi.MUPParking.MUPParkingWebServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MUPParkingWebServiceInterfaceClient : System.ServiceModel.ClientBase<PG.Servisi.MUPParking.MUPParkingWebServiceInterface>, PG.Servisi.MUPParking.MUPParkingWebServiceInterface {
        
        public MUPParkingWebServiceInterfaceClient() {
        }
        
        public MUPParkingWebServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MUPParkingWebServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MUPParkingWebServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MUPParkingWebServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PG.Servisi.MUPParking.VoziloResponse PG.Servisi.MUPParking.MUPParkingWebServiceInterface.Vozilo(PG.Servisi.MUPParking.VoziloRequest request) {
            return base.Channel.Vozilo(request);
        }
        
        public PG.Servisi.MUPParking.Odgovor Vozilo(PG.Servisi.MUPParking.UpitIdentifikacija zaglavlje, PG.Servisi.MUPParking.PretragaParams Vozilo1, out int Status, out string StatusMessage) {
            PG.Servisi.MUPParking.VoziloRequest inValue = new PG.Servisi.MUPParking.VoziloRequest();
            inValue.zaglavlje = zaglavlje;
            inValue.Vozilo = Vozilo1;
            PG.Servisi.MUPParking.VoziloResponse retVal = ((PG.Servisi.MUPParking.MUPParkingWebServiceInterface)(this)).Vozilo(inValue);
            Status = retVal.Status;
            StatusMessage = retVal.StatusMessage;
            return retVal.OdgovorVozilo;
        }
        
        public System.Threading.Tasks.Task<PG.Servisi.MUPParking.VoziloResponse> VoziloAsync(PG.Servisi.MUPParking.VoziloRequest request) {
            return base.Channel.VoziloAsync(request);
        }
    }
}
