//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG.Servisi.GOService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_3DLista", Namespace="http://schemas.datacontract.org/2004/07/GO.Servisi")]
    [System.SerializableAttribute()]
    public partial class _3DLista : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis {
            get {
                return this.OpisField;
            }
            set {
                if ((object.ReferenceEquals(this.OpisField, value) != true)) {
                    this.OpisField = value;
                    this.RaisePropertyChanged("Opis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_2DLista", Namespace="http://schemas.datacontract.org/2004/07/GO.Servisi")]
    [System.SerializableAttribute()]
    public partial class _2DLista : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NapomenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Napomena {
            get {
                return this.NapomenaField;
            }
            set {
                if ((object.ReferenceEquals(this.NapomenaField, value) != true)) {
                    this.NapomenaField = value;
                    this.RaisePropertyChanged("Napomena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_Klasifikacija", Namespace="http://schemas.datacontract.org/2004/07/GO.Servisi")]
    [System.SerializableAttribute()]
    public partial class _Klasifikacija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AutomatskiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AutomatskiRijesenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDGrupeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDKlasifikacijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDPredloskaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTipaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDZakonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._Korisnik> KorisniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NalogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NijeJavnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ObrisanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VoziloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Automatski {
            get {
                return this.AutomatskiField;
            }
            set {
                if ((this.AutomatskiField.Equals(value) != true)) {
                    this.AutomatskiField = value;
                    this.RaisePropertyChanged("Automatski");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AutomatskiRijeseno {
            get {
                return this.AutomatskiRijesenoField;
            }
            set {
                if ((this.AutomatskiRijesenoField.Equals(value) != true)) {
                    this.AutomatskiRijesenoField = value;
                    this.RaisePropertyChanged("AutomatskiRijeseno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupa {
            get {
                return this.GrupaField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupaField, value) != true)) {
                    this.GrupaField = value;
                    this.RaisePropertyChanged("Grupa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDGrupe {
            get {
                return this.IDGrupeField;
            }
            set {
                if ((this.IDGrupeField.Equals(value) != true)) {
                    this.IDGrupeField = value;
                    this.RaisePropertyChanged("IDGrupe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDKlasifikacije {
            get {
                return this.IDKlasifikacijeField;
            }
            set {
                if ((this.IDKlasifikacijeField.Equals(value) != true)) {
                    this.IDKlasifikacijeField = value;
                    this.RaisePropertyChanged("IDKlasifikacije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDPredloska {
            get {
                return this.IDPredloskaField;
            }
            set {
                if ((this.IDPredloskaField.Equals(value) != true)) {
                    this.IDPredloskaField = value;
                    this.RaisePropertyChanged("IDPredloska");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTipa {
            get {
                return this.IDTipaField;
            }
            set {
                if ((this.IDTipaField.Equals(value) != true)) {
                    this.IDTipaField = value;
                    this.RaisePropertyChanged("IDTipa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDZakona {
            get {
                return this.IDZakonaField;
            }
            set {
                if ((this.IDZakonaField.Equals(value) != true)) {
                    this.IDZakonaField = value;
                    this.RaisePropertyChanged("IDZakona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._Korisnik> Korisnici {
            get {
                return this.KorisniciField;
            }
            set {
                if ((object.ReferenceEquals(this.KorisniciField, value) != true)) {
                    this.KorisniciField = value;
                    this.RaisePropertyChanged("Korisnici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Nalog {
            get {
                return this.NalogField;
            }
            set {
                if ((this.NalogField.Equals(value) != true)) {
                    this.NalogField = value;
                    this.RaisePropertyChanged("Nalog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NijeJavno {
            get {
                return this.NijeJavnoField;
            }
            set {
                if ((this.NijeJavnoField.Equals(value) != true)) {
                    this.NijeJavnoField = value;
                    this.RaisePropertyChanged("NijeJavno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Obrisana {
            get {
                return this.ObrisanaField;
            }
            set {
                if ((this.ObrisanaField.Equals(value) != true)) {
                    this.ObrisanaField = value;
                    this.RaisePropertyChanged("Obrisana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis {
            get {
                return this.OpisField;
            }
            set {
                if ((object.ReferenceEquals(this.OpisField, value) != true)) {
                    this.OpisField = value;
                    this.RaisePropertyChanged("Opis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Vozilo {
            get {
                return this.VoziloField;
            }
            set {
                if ((this.VoziloField.Equals(value) != true)) {
                    this.VoziloField = value;
                    this.RaisePropertyChanged("Vozilo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_Korisnik", Namespace="http://schemas.datacontract.org/2004/07/GO.Servisi")]
    [System.SerializableAttribute()]
    public partial class _Korisnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktivanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarSlikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BlokiranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatumRodenjaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.ObservableCollection<int> DetaljnePrivilegijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDKorisnikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDPazigradField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPrivilegijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._Klasifikacija> KlasfikacijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LozinkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobitelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NapomenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivDrustvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OdbijenSMSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PretragaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivilegijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SMSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktivan {
            get {
                return this.AktivanField;
            }
            set {
                if ((this.AktivanField.Equals(value) != true)) {
                    this.AktivanField = value;
                    this.RaisePropertyChanged("Aktivan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Avatar {
            get {
                return this.AvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarField, value) != true)) {
                    this.AvatarField = value;
                    this.RaisePropertyChanged("Avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarSlika {
            get {
                return this.AvatarSlikaField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarSlikaField, value) != true)) {
                    this.AvatarSlikaField = value;
                    this.RaisePropertyChanged("AvatarSlika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Blokiran {
            get {
                return this.BlokiranField;
            }
            set {
                if ((this.BlokiranField.Equals(value) != true)) {
                    this.BlokiranField = value;
                    this.RaisePropertyChanged("Blokiran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatumRodenja {
            get {
                return this.DatumRodenjaField;
            }
            set {
                if ((this.DatumRodenjaField.Equals(value) != true)) {
                    this.DatumRodenjaField = value;
                    this.RaisePropertyChanged("DatumRodenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<int> DetaljnePrivilegije {
            get {
                return this.DetaljnePrivilegijeField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaljnePrivilegijeField, value) != true)) {
                    this.DetaljnePrivilegijeField = value;
                    this.RaisePropertyChanged("DetaljnePrivilegije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDKorisnika {
            get {
                return this.IDKorisnikaField;
            }
            set {
                if ((this.IDKorisnikaField.Equals(value) != true)) {
                    this.IDKorisnikaField = value;
                    this.RaisePropertyChanged("IDKorisnika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDPazigrad {
            get {
                return this.IDPazigradField;
            }
            set {
                if ((this.IDPazigradField.Equals(value) != true)) {
                    this.IDPazigradField = value;
                    this.RaisePropertyChanged("IDPazigrad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPrivilegije {
            get {
                return this.IDPrivilegijeField;
            }
            set {
                if ((this.IDPrivilegijeField.Equals(value) != true)) {
                    this.IDPrivilegijeField = value;
                    this.RaisePropertyChanged("IDPrivilegije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._Klasifikacija> Klasfikacije {
            get {
                return this.KlasfikacijeField;
            }
            set {
                if ((object.ReferenceEquals(this.KlasfikacijeField, value) != true)) {
                    this.KlasfikacijeField = value;
                    this.RaisePropertyChanged("Klasfikacije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lozinka {
            get {
                return this.LozinkaField;
            }
            set {
                if ((object.ReferenceEquals(this.LozinkaField, value) != true)) {
                    this.LozinkaField = value;
                    this.RaisePropertyChanged("Lozinka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobitel {
            get {
                return this.MobitelField;
            }
            set {
                if ((object.ReferenceEquals(this.MobitelField, value) != true)) {
                    this.MobitelField = value;
                    this.RaisePropertyChanged("Mobitel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Napomena {
            get {
                return this.NapomenaField;
            }
            set {
                if ((object.ReferenceEquals(this.NapomenaField, value) != true)) {
                    this.NapomenaField = value;
                    this.RaisePropertyChanged("Napomena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivDrustva {
            get {
                return this.NazivDrustvaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivDrustvaField, value) != true)) {
                    this.NazivDrustvaField = value;
                    this.RaisePropertyChanged("NazivDrustva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OdbijenSMS {
            get {
                return this.OdbijenSMSField;
            }
            set {
                if ((this.OdbijenSMSField.Equals(value) != true)) {
                    this.OdbijenSMSField = value;
                    this.RaisePropertyChanged("OdbijenSMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pretraga {
            get {
                return this.PretragaField;
            }
            set {
                if ((object.ReferenceEquals(this.PretragaField, value) != true)) {
                    this.PretragaField = value;
                    this.RaisePropertyChanged("Pretraga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Privilegija {
            get {
                return this.PrivilegijaField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivilegijaField, value) != true)) {
                    this.PrivilegijaField = value;
                    this.RaisePropertyChanged("Privilegija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SMS {
            get {
                return this.SMSField;
            }
            set {
                if ((this.SMSField.Equals(value) != true)) {
                    this.SMSField = value;
                    this.RaisePropertyChanged("SMS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_Predmet", Namespace="http://schemas.datacontract.org/2004/07/GO.Servisi")]
    [System.SerializableAttribute()]
    public partial class _Predmet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AlarmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnonimnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatumPredmetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumVrijemeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatumZatvaranjaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._2DLista> DokumentiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDGrupeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDIzvoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDKlasifikacijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDLokacijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDObjektaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPredmetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPrijaviteljaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDStatusaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTipaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDVanjskogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDZaduzenogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IkonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool JavnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KlasifikacijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KomentiranjeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PG.Servisi.GOService._2DLista KomunalniObjektField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MjestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaslovPredmetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NoviField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PazigradField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrijaviteljField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistracijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifraPredmetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TekstPrijaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UlicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZaduzenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Alarm {
            get {
                return this.AlarmField;
            }
            set {
                if ((this.AlarmField.Equals(value) != true)) {
                    this.AlarmField = value;
                    this.RaisePropertyChanged("Alarm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Anonimno {
            get {
                return this.AnonimnoField;
            }
            set {
                if ((this.AnonimnoField.Equals(value) != true)) {
                    this.AnonimnoField = value;
                    this.RaisePropertyChanged("Anonimno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatumPredmeta {
            get {
                return this.DatumPredmetaField;
            }
            set {
                if ((object.ReferenceEquals(this.DatumPredmetaField, value) != true)) {
                    this.DatumPredmetaField = value;
                    this.RaisePropertyChanged("DatumPredmeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumVrijeme {
            get {
                return this.DatumVrijemeField;
            }
            set {
                if ((this.DatumVrijemeField.Equals(value) != true)) {
                    this.DatumVrijemeField = value;
                    this.RaisePropertyChanged("DatumVrijeme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatumZatvaranja {
            get {
                return this.DatumZatvaranjaField;
            }
            set {
                if ((this.DatumZatvaranjaField.Equals(value) != true)) {
                    this.DatumZatvaranjaField = value;
                    this.RaisePropertyChanged("DatumZatvaranja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._2DLista> Dokumenti {
            get {
                return this.DokumentiField;
            }
            set {
                if ((object.ReferenceEquals(this.DokumentiField, value) != true)) {
                    this.DokumentiField = value;
                    this.RaisePropertyChanged("Dokumenti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupa {
            get {
                return this.GrupaField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupaField, value) != true)) {
                    this.GrupaField = value;
                    this.RaisePropertyChanged("Grupa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDGrupe {
            get {
                return this.IDGrupeField;
            }
            set {
                if ((this.IDGrupeField.Equals(value) != true)) {
                    this.IDGrupeField = value;
                    this.RaisePropertyChanged("IDGrupe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDIzvora {
            get {
                return this.IDIzvoraField;
            }
            set {
                if ((this.IDIzvoraField.Equals(value) != true)) {
                    this.IDIzvoraField = value;
                    this.RaisePropertyChanged("IDIzvora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDKlasifikacije {
            get {
                return this.IDKlasifikacijeField;
            }
            set {
                if ((this.IDKlasifikacijeField.Equals(value) != true)) {
                    this.IDKlasifikacijeField = value;
                    this.RaisePropertyChanged("IDKlasifikacije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDLokacije {
            get {
                return this.IDLokacijeField;
            }
            set {
                if ((this.IDLokacijeField.Equals(value) != true)) {
                    this.IDLokacijeField = value;
                    this.RaisePropertyChanged("IDLokacije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDObjekta {
            get {
                return this.IDObjektaField;
            }
            set {
                if ((this.IDObjektaField.Equals(value) != true)) {
                    this.IDObjektaField = value;
                    this.RaisePropertyChanged("IDObjekta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPredmeta {
            get {
                return this.IDPredmetaField;
            }
            set {
                if ((this.IDPredmetaField.Equals(value) != true)) {
                    this.IDPredmetaField = value;
                    this.RaisePropertyChanged("IDPredmeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPrijavitelja {
            get {
                return this.IDPrijaviteljaField;
            }
            set {
                if ((this.IDPrijaviteljaField.Equals(value) != true)) {
                    this.IDPrijaviteljaField = value;
                    this.RaisePropertyChanged("IDPrijavitelja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDStatusa {
            get {
                return this.IDStatusaField;
            }
            set {
                if ((this.IDStatusaField.Equals(value) != true)) {
                    this.IDStatusaField = value;
                    this.RaisePropertyChanged("IDStatusa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTipa {
            get {
                return this.IDTipaField;
            }
            set {
                if ((this.IDTipaField.Equals(value) != true)) {
                    this.IDTipaField = value;
                    this.RaisePropertyChanged("IDTipa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDVanjskog {
            get {
                return this.IDVanjskogField;
            }
            set {
                if ((this.IDVanjskogField.Equals(value) != true)) {
                    this.IDVanjskogField = value;
                    this.RaisePropertyChanged("IDVanjskog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDZaduzenog {
            get {
                return this.IDZaduzenogField;
            }
            set {
                if ((this.IDZaduzenogField.Equals(value) != true)) {
                    this.IDZaduzenogField = value;
                    this.RaisePropertyChanged("IDZaduzenog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ikona {
            get {
                return this.IkonaField;
            }
            set {
                if ((object.ReferenceEquals(this.IkonaField, value) != true)) {
                    this.IkonaField = value;
                    this.RaisePropertyChanged("Ikona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Javno {
            get {
                return this.JavnoField;
            }
            set {
                if ((this.JavnoField.Equals(value) != true)) {
                    this.JavnoField = value;
                    this.RaisePropertyChanged("Javno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kbr {
            get {
                return this.KbrField;
            }
            set {
                if ((object.ReferenceEquals(this.KbrField, value) != true)) {
                    this.KbrField = value;
                    this.RaisePropertyChanged("Kbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Klasifikacija {
            get {
                return this.KlasifikacijaField;
            }
            set {
                if ((object.ReferenceEquals(this.KlasifikacijaField, value) != true)) {
                    this.KlasifikacijaField = value;
                    this.RaisePropertyChanged("Klasifikacija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Komentiranje {
            get {
                return this.KomentiranjeField;
            }
            set {
                if ((this.KomentiranjeField.Equals(value) != true)) {
                    this.KomentiranjeField = value;
                    this.RaisePropertyChanged("Komentiranje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PG.Servisi.GOService._2DLista KomunalniObjekt {
            get {
                return this.KomunalniObjektField;
            }
            set {
                if ((object.ReferenceEquals(this.KomunalniObjektField, value) != true)) {
                    this.KomunalniObjektField = value;
                    this.RaisePropertyChanged("KomunalniObjekt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marker {
            get {
                return this.MarkerField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkerField, value) != true)) {
                    this.MarkerField = value;
                    this.RaisePropertyChanged("Marker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mjesto {
            get {
                return this.MjestoField;
            }
            set {
                if ((object.ReferenceEquals(this.MjestoField, value) != true)) {
                    this.MjestoField = value;
                    this.RaisePropertyChanged("Mjesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NaslovPredmeta {
            get {
                return this.NaslovPredmetaField;
            }
            set {
                if ((object.ReferenceEquals(this.NaslovPredmetaField, value) != true)) {
                    this.NaslovPredmetaField = value;
                    this.RaisePropertyChanged("NaslovPredmeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Novi {
            get {
                return this.NoviField;
            }
            set {
                if ((this.NoviField.Equals(value) != true)) {
                    this.NoviField = value;
                    this.RaisePropertyChanged("Novi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pazigrad {
            get {
                return this.PazigradField;
            }
            set {
                if ((this.PazigradField.Equals(value) != true)) {
                    this.PazigradField = value;
                    this.RaisePropertyChanged("Pazigrad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Posta {
            get {
                return this.PostaField;
            }
            set {
                if ((object.ReferenceEquals(this.PostaField, value) != true)) {
                    this.PostaField = value;
                    this.RaisePropertyChanged("Posta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prijavitelj {
            get {
                return this.PrijaviteljField;
            }
            set {
                if ((object.ReferenceEquals(this.PrijaviteljField, value) != true)) {
                    this.PrijaviteljField = value;
                    this.RaisePropertyChanged("Prijavitelj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Registracija {
            get {
                return this.RegistracijaField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistracijaField, value) != true)) {
                    this.RegistracijaField = value;
                    this.RaisePropertyChanged("Registracija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SifraPredmeta {
            get {
                return this.SifraPredmetaField;
            }
            set {
                if ((object.ReferenceEquals(this.SifraPredmetaField, value) != true)) {
                    this.SifraPredmetaField = value;
                    this.RaisePropertyChanged("SifraPredmeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag {
            get {
                return this.TagField;
            }
            set {
                if ((object.ReferenceEquals(this.TagField, value) != true)) {
                    this.TagField = value;
                    this.RaisePropertyChanged("Tag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TekstPrijave {
            get {
                return this.TekstPrijaveField;
            }
            set {
                if ((object.ReferenceEquals(this.TekstPrijaveField, value) != true)) {
                    this.TekstPrijaveField = value;
                    this.RaisePropertyChanged("TekstPrijave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulica {
            get {
                return this.UlicaField;
            }
            set {
                if ((object.ReferenceEquals(this.UlicaField, value) != true)) {
                    this.UlicaField = value;
                    this.RaisePropertyChanged("Ulica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zaduzen {
            get {
                return this.ZaduzenField;
            }
            set {
                if ((object.ReferenceEquals(this.ZaduzenField, value) != true)) {
                    this.ZaduzenField = value;
                    this.RaisePropertyChanged("Zaduzen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GOService.IGOPazigrad")]
    public interface IGOPazigrad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGOPazigrad/Gradovi", ReplyAction="http://tempuri.org/IGOPazigrad/GradoviResponse")]
        System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._3DLista> Gradovi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGOPazigrad/Gradovi", ReplyAction="http://tempuri.org/IGOPazigrad/GradoviResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._3DLista>> GradoviAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGOPazigrad/Grupe", ReplyAction="http://tempuri.org/IGOPazigrad/GrupeResponse")]
        System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._2DLista> Grupe(string grad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGOPazigrad/Grupe", ReplyAction="http://tempuri.org/IGOPazigrad/GrupeResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._2DLista>> GrupeAsync(string grad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGOPazigrad/DodajKlasifikaciju", ReplyAction="http://tempuri.org/IGOPazigrad/DodajKlasifikacijuResponse")]
        int DodajKlasifikaciju(string grad, PG.Servisi.GOService._Klasifikacija klas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGOPazigrad/DodajKlasifikaciju", ReplyAction="http://tempuri.org/IGOPazigrad/DodajKlasifikacijuResponse")]
        System.Threading.Tasks.Task<int> DodajKlasifikacijuAsync(string grad, PG.Servisi.GOService._Klasifikacija klas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGOPazigrad/DodajKorisnika", ReplyAction="http://tempuri.org/IGOPazigrad/DodajKorisnikaResponse")]
        int DodajKorisnika(string grad, PG.Servisi.GOService._Korisnik korisnik, System.Collections.ObjectModel.ObservableCollection<int> idKlasifikacije);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGOPazigrad/DodajKorisnika", ReplyAction="http://tempuri.org/IGOPazigrad/DodajKorisnikaResponse")]
        System.Threading.Tasks.Task<int> DodajKorisnikaAsync(string grad, PG.Servisi.GOService._Korisnik korisnik, System.Collections.ObjectModel.ObservableCollection<int> idKlasifikacije);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGOPazigrad/NoviPredmet", ReplyAction="http://tempuri.org/IGOPazigrad/NoviPredmetResponse")]
        int NoviPredmet(string grad, PG.Servisi.GOService._Predmet predmet, System.Collections.ObjectModel.ObservableCollection<byte[]> slike, bool proslijedi, bool hub);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGOPazigrad/NoviPredmet", ReplyAction="http://tempuri.org/IGOPazigrad/NoviPredmetResponse")]
        System.Threading.Tasks.Task<int> NoviPredmetAsync(string grad, PG.Servisi.GOService._Predmet predmet, System.Collections.ObjectModel.ObservableCollection<byte[]> slike, bool proslijedi, bool hub);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGOPazigradChannel : PG.Servisi.GOService.IGOPazigrad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GOPazigradClient : System.ServiceModel.ClientBase<PG.Servisi.GOService.IGOPazigrad>, PG.Servisi.GOService.IGOPazigrad {
        
        public GOPazigradClient() {
        }
        
        public GOPazigradClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GOPazigradClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GOPazigradClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GOPazigradClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._3DLista> Gradovi() {
            return base.Channel.Gradovi();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._3DLista>> GradoviAsync() {
            return base.Channel.GradoviAsync();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._2DLista> Grupe(string grad) {
            return base.Channel.Grupe(grad);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<PG.Servisi.GOService._2DLista>> GrupeAsync(string grad) {
            return base.Channel.GrupeAsync(grad);
        }
        
        public int DodajKlasifikaciju(string grad, PG.Servisi.GOService._Klasifikacija klas) {
            return base.Channel.DodajKlasifikaciju(grad, klas);
        }
        
        public System.Threading.Tasks.Task<int> DodajKlasifikacijuAsync(string grad, PG.Servisi.GOService._Klasifikacija klas) {
            return base.Channel.DodajKlasifikacijuAsync(grad, klas);
        }
        
        public int DodajKorisnika(string grad, PG.Servisi.GOService._Korisnik korisnik, System.Collections.ObjectModel.ObservableCollection<int> idKlasifikacije) {
            return base.Channel.DodajKorisnika(grad, korisnik, idKlasifikacije);
        }
        
        public System.Threading.Tasks.Task<int> DodajKorisnikaAsync(string grad, PG.Servisi.GOService._Korisnik korisnik, System.Collections.ObjectModel.ObservableCollection<int> idKlasifikacije) {
            return base.Channel.DodajKorisnikaAsync(grad, korisnik, idKlasifikacije);
        }
        
        public int NoviPredmet(string grad, PG.Servisi.GOService._Predmet predmet, System.Collections.ObjectModel.ObservableCollection<byte[]> slike, bool proslijedi, bool hub) {
            return base.Channel.NoviPredmet(grad, predmet, slike, proslijedi, hub);
        }
        
        public System.Threading.Tasks.Task<int> NoviPredmetAsync(string grad, PG.Servisi.GOService._Predmet predmet, System.Collections.ObjectModel.ObservableCollection<byte[]> slike, bool proslijedi, bool hub) {
            return base.Channel.NoviPredmetAsync(grad, predmet, slike, proslijedi, hub);
        }
    }
}
